### ISSUE TITLE
Example checkpoint file is missing

### ISSUE THREAD

**Issue by trenton** [assafshocher/InGAN#1]
When following the `download the example checkpoint file` link in the Quick example, I get this error page:

```
Not Found

The requested URL /~vision/ingan/resource/checkpoint_0075000.pth.tar was not found on this server.

Additionally, a 302 Found error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by san-guy** [comment]
Yeah, facing the same issue here as well.

**Comment by assafshocher** [comment]
Thanks for pointing this out!
Will fix in a few days (when back from ICCV)

**Comment by assafshocher** [comment]
Hi guys,
It was just a URL typo. now fixed.
Thanks again for pointing this out!
