### ISSUE TITLE
Checkpoint file cannot be downloaded

### ISSUE THREAD

**Issue by stephanboner** [assafshocher/InGAN#7]
Hi there,

Every time I try to download the File "checkpoint_0075000.pth.tar" for the fruits-example from [here](http://www.wisdom.weizmann.ac.il/~vision/ingan/resources/checkpoint_0075000.pth.tar), the download gets interrupted and then the tar-file is invalid. Tried it via my local computer (wget, curl, browser) and the cluster I'm using (wget, curl) but everytime I'm facing the same issue having a corrupt tar-file. Could you please upload the checkpoint-file somewhere else?

Thank you very much and cheers,
Stephan

**Comment by assafshocher** [comment]
I can't reproduce this problem, I get no problem downloading it.
However, I  also put it on Dropbox in case that works out better:
https://www.dropbox.com/s/5fk4fpvs68qbiv8/checkpoint_0075000.pth.tar?dl=0
Try downloading form this link

**Comment by stephanboner** [comment]
Thank you very much, that worked now 😊
